In [5]:
import scipy as sp
import scipy.sparse as ss
import numpy as np

In [25]:
row  = np.array([0, 3, 1, 0])
col  = np.array([0, 3, 1, 2])
data = np.array([4, 5, 7, 9])
a=ss.coo_matrix((data, (row, col)), shape=(2000,2000))

In [22]:
(a+a).toarray()

array([[ 8,  0, 18, ...,  0,  0,  0],
       [ 0, 14,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=int32)

In [26]:
%timeit (a+a)

223 µs ± 3.66 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [28]:
k=a.toarray()

In [30]:
%timeit (k+k)

5.84 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [1]:
print({2,1})

{1, 2}


In [9]:
import numpy as np

a = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6],[7,8,9,6]])

#array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])
print(a)
a[np.triu_indices(a.shape[0],k=1)]

# this returns the following

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 6]
 [7 8 9 6]]


array([2, 3, 4, 6, 5, 6])